Cargo.lock
applets/cosmic-app-list/src/apps_container/mod.rs
applets/cosmic-app-list/src/dock_list/mod.rs
applets/cosmic-app-list/src/dock_popover/mod.rs
applets/cosmic-app-list/src/main.rs
applets/cosmic-app-list/src/wayland.rs
applets/cosmic-applet-audio/src/main.rs
applets/cosmic-applet-battery/src/main.rs
applets/cosmic-applet-power/src/main.rs
applets/cosmic-applet-workspaces/src/main.rs
applets/cosmic-applet-workspaces/src/wayland.rs
applets/cosmic-applet-workspaces/src/window/mod.rs
applets/cosmic-applet-workspaces/src/workspace_list/imp.rs
applets/cosmic-applet-workspaces/src/workspace_list/mod.rs
applets/cosmic-panel-button/src/apps_window/mod.rs
libcosmic-applet/src/button.rs

This makes the necessary changes for using the new panel config env vars. Currently, the applets will only work when running on a single monitor. Do we want to work on support for multiple monitors before merging these changes?

WIP: Panel config changes

---

applets/cosmic-applet-time/Cargo.lock
applets/cosmic-applet-time/Cargo.toml
applets/cosmic-applet-time/src/main.rs

Fixes the time applet to be the right size and style. 
Requires https://github.com/pop-os/libcosmic/pull/47 and will need a commit pushed to fix build after that is merged.

Time to fix sytling

---

Cargo.lock
cosmic-app-list/Cargo.toml
cosmic-app-list/src/app.rs
cosmic-applet-audio/src/main.rs
cosmic-applet-battery/src/app.rs
cosmic-applet-graphics/src/main.rs
cosmic-applet-graphics/src/window.rs
cosmic-applet-network/src/app.rs
cosmic-applet-network/src/network_manager/current_networks.rs
cosmic-applet-notifications/src/main.rs
cosmic-applet-power/src/main.rs
cosmic-applet-time/src/main.rs
cosmic-applet-workspaces/src/components/app.rs

This updates applets to use the auto-sizing popups, and does some cleanup.

update applets using latest libcosmic auto-sizing popups

---

cosmic-applet-power/src/main.rs

A tiny fix, no point in using the macro to push widgets anyway.

Fix power container build code

---

Cargo.lock
cosmic-applet-audio/Cargo.toml
cosmic-applet-battery/Cargo.toml
cosmic-applet-graphics/Cargo.toml
cosmic-applet-network/Cargo.toml
cosmic-applet-power/Cargo.toml
cosmic-applet-workspaces/Cargo.toml
cosmic-applet-workspaces/src/wayland.rs

Needs some testing to make sure it is working as well as the previous version. (The compositor seems to be reporting somewhat funny workspace information in my current session: https://github.com/pop-os/cosmic-comp/issues/49)

Use `cosmic-client-toolkit` helpers in workspace applet

---

Cargo.lock
cosmic-app-list/src/app.rs
cosmic-app-list/src/toplevel_subscription.rs
cosmic-applet-audio/src/main.rs
cosmic-applet-audio/src/pulse.rs
cosmic-applet-battery/Cargo.toml
cosmic-applet-battery/src/app.rs
cosmic-applet-battery/src/backlight.rs
cosmic-applet-battery/src/upower_device.rs
cosmic-applet-battery/src/upower_kbdbacklight.rs
cosmic-applet-graphics/src/window.rs
cosmic-applet-power/Cargo.toml
cosmic-applet-workspaces/src/components/app.rs
cosmic-applet-workspaces/src/wayland.rs

This shouldn't change behavior, or touch applets others are currently working on.

Fix some warnings and clippy lints

---

cosmic-applet-power/src/main.rs

mostly just border radius and padding adjustments

refactor: power applet more like mockup

---

cosmic-app-list/i18n/fa/cosmic_app_list.ftl
cosmic-applet-battery/i18n/fa/cosmic_applet_battery.ftl
cosmic-applet-graphics/i18n/fa/cosmic_applet_graphics.ftl
cosmic-applet-network/i18n/fa/cosmic_applet_network.ftl
cosmic-applet-workspaces/i18n/fa/cosmic_applet_workspaces.ftl

I love Pop_Os! Can't wait to try the new Cosmic desktop! :))

Translate applets to persian!

---

Cargo.lock
Cargo.toml
cosmic-applet-bluetooth/Cargo.toml
cosmic-applet-bluetooth/data/com.system76.CosmicAppletBluetooth.desktop
cosmic-applet-bluetooth/data/icons/com.system76.CosmicAppletBluetooth.svg
cosmic-applet-bluetooth/data/resources/resources.gresource.xml
cosmic-applet-bluetooth/i18n.toml
cosmic-applet-bluetooth/i18n/en/cosmic_applet_bluetooth.ftl
cosmic-applet-bluetooth/src/app.rs
cosmic-applet-bluetooth/src/bluetooth.rs
cosmic-applet-bluetooth/src/config.rs
cosmic-applet-bluetooth/src/localize.rs
cosmic-applet-bluetooth/src/main.rs
debian/control
justfile

The bluetooth applet seems to work pretty well now :)

bluetooth applet

---

cosmic-applet-audio/src/main.rs
cosmic-applet-audio/src/pulse.rs

allow switching input/output and update outputs/inputs when the popup or revealer is toggled. This also moves the input / output active streams, and seemed to work ok for me when i tested output switching.

feat(audio): allow switching input/output 

---

cosmic-applet-audio/src/pulse.rs

fix(audio): panic on events without a connection

---

Cargo.lock
Cargo.toml
applets/cosmic-applet-status-area/src/status_menu.rs
cosmic-applet-status-area/Cargo.toml
cosmic-applet-status-area/data/com.system76.CosmicAppletStatusArea.desktop
cosmic-applet-status-area/data/icons/scalable/app/com.system76.CosmicAppletStatusArea.svg
cosmic-applet-status-area/src/components/app.rs
cosmic-applet-status-area/src/components/mod.rs
cosmic-applet-status-area/src/components/status_menu.rs
cosmic-applet-status-area/src/main.rs
cosmic-applet-status-area/src/subscriptions/mod.rs
cosmic-applet-status-area/src/subscriptions/status_notifier_item.rs
cosmic-applet-status-area/src/subscriptions/status_notifier_watcher/client.rs
cosmic-applet-status-area/src/subscriptions/status_notifier_watcher/mod.rs
cosmic-applet-status-area/src/subscriptions/status_notifier_watcher/server.rs
justfile

Needs correct sizing for popup, and the style and behavior of the menu contents needs to be finished.

Iced port of status area applet

---

cosmic-app-list/Cargo.toml
cosmic-app-list/src/app.rs

Revival of #120 due to badly named branch name getting stuck on CI

Applist fix icons

---

cosmic-applet-battery/src/app.rs
cosmic-applet-bluetooth/src/app.rs
cosmic-applet-graphics/src/window.rs
cosmic-applet-network/i18n/en/cosmic_applet_network.ftl
cosmic-applet-network/src/app.rs
cosmic-applet-notifications/i18n/en/cosmic_applet_notifications.ftl
cosmic-applet-notifications/src/main.rs
cosmic-applet-power/src/main.rs

Some more miscellaneous layout improvements.

Layout jammy

---

cosmic-applet-power/src/main.rs

Adds the countdown to the confirm popup

cosmic-applet-power: countdown

---

cosmic-app-list/i18n/ru/cosmic_app_list.ftl
cosmic-applet-power/i18n/ru/cosmic_applet_power.ftl
cosmic-applet-tiling/i18n/ru/cosmic_applet_tiling.ftl

Some of the translations I sent earlier were not quite accurate, sorry.

Correction of the translation

---

cosmic-app-list/src/app.rs
cosmic-app-list/src/config.rs
cosmic-app-list/src/wayland_handler.rs
cosmic-app-list/src/wayland_subscription.rs
cosmic-applet-audio/src/main.rs
cosmic-applet-audio/src/mpris_subscription.rs
cosmic-applet-audio/src/pulse.rs
cosmic-applet-battery/src/app.rs
cosmic-applet-bluetooth/src/app.rs
cosmic-applet-bluetooth/src/bluetooth.rs
cosmic-applet-graphics/src/window.rs
cosmic-applet-network/src/app.rs
cosmic-applet-network/src/network_manager/active_conns.rs
cosmic-applet-network/src/network_manager/available_wifi.rs
cosmic-applet-network/src/network_manager/current_networks.rs
cosmic-applet-network/src/network_manager/devices.rs
cosmic-applet-network/src/network_manager/mod.rs
cosmic-applet-network/src/network_manager/wireless_enabled.rs
cosmic-applet-notifications/src/main.rs
cosmic-applet-power/src/main.rs
cosmic-applet-status-area/src/components/status_menu.rs
cosmic-applet-status-area/src/subscriptions/status_notifier_item.rs
cosmic-applet-status-area/src/subscriptions/status_notifier_watcher/client.rs
cosmic-applet-status-area/src/subscriptions/status_notifier_watcher/server.rs
cosmic-applet-tiling/src/window.rs
cosmic-applet-time/src/window.rs
cosmic-applet-workspaces/src/components/app.rs
cosmic-panel-button/src/main.rs

various code quality improvements.
commits are separated for ease of review, but should be squashed for merge.

Code quality

---

.github/dependabot.yml
.github/workflows/ci.yml
.gitignore
cosmic-app-list/src/app.rs
cosmic-applet-audio/src/mpris_subscription.rs
cosmic-applet-audio/src/pulse.rs
cosmic-applet-network/src/app.rs
cosmic-applet-network/src/network_manager/current_networks.rs
cosmic-applet-status-area/src/components/app.rs
cosmic-applet-tiling/src/window.rs
cosmic-applet-workspaces/src/components/app.rs
cosmic-panel-button/src/main.rs

this PR should ensure that the code quality improvements introduced in #154 *stay* fixed
I'll leave this as a draft for now since there are still a few errors failing the checks. I also suspect I'll need to update the github action to install some missing packages required for the build. I can test that in my own fork

add linting CI jobs

---

cosmic-app-list/i18n/pl/cosmic_app_list.ftl

Basic Polish translation, there isn't any

Create cosmic_app_list.ftl PL translation

---

cosmic-applet-battery/i18n/pl/cosmic_applet_battery.ftl

There is no Polish translation, here is pretty basic one.

Add cosmic_applet_battery.ftl PL Translation

---

cosmic-applet-bluetooth/i18n/pl/cosmic_applet_bluetooth.ftl

Here is basic Polish translation, there wasn't any so i wrote one.

Add cosmic_applet_bluetooth.ftl PL Translation

---

cosmic-applet-graphics/i18n/pl/cosmic_applet_graphics.ftl

Pretty basic Polish translation, wasn't any so i added one.

Add cosmic_applet_graphics.ftl PL Translation

---

cosmic-applet-audio/i18n/pl/cosmic_applet_audio.ftl

There is no Polish translation, added basic one.

Add cosmic_applet_audio PL translation

---

Cargo.lock
Cargo.toml

this fixes the workspace list applet

fix: update libcosmic and cosmic-protocols

---

cosmic-applet-notifications/i18n/pl/cosmic_applet_notifications.ftl

Added basic Polish translation to fill the void.

Add cosmic_applet_notifications.ftl PL translation

---

Cargo.lock
Cargo.toml
cosmic-app-list/src/app.rs
cosmic-applet-audio/src/main.rs
cosmic-applet-battery/src/app.rs
cosmic-applet-graphics/src/window.rs
cosmic-applet-power/src/main.rs
cosmic-applet-status-area/src/components/app.rs
cosmic-applet-status-area/src/components/status_menu.rs
cosmic-applet-time/src/window.rs
cosmic-applet-workspaces/src/components/app.rs

depends on https://github.com/pop-os/cosmic-time/pull/19 & https://github.com/pop-os/libcosmic/pull/287

chore: update libcosmic

---

cosmic-app-list/src/app.rs

fix(app-list): load apps so that they match the config order

---

cosmic-applet-audio/src/mpris_subscription.rs

fix(audio): no media player will be chosen unless paused or playing

---

cosmic-app-list/src/app.rs

Fixes https://github.com/pop-os/cosmic-applets/issues/207

Limit number of app list dots to 3

---

cosmic-app-list/i18n/pl/cosmic_app_list.ftl

Update cosmic_app_list.ftl PL translation

---

Cargo.lock
Cargo.toml
cosmic-applet-minimize/src/wayland_handler.rs

Requires https://github.com/pop-os/cosmic-protocols/pull/24.

cosmic-screencopy-v2

---

cosmic-applet-battery/src/app.rs
cosmic-applet-battery/src/backlight.rs
cosmic-applet-battery/src/upower_kbdbacklight.rs
cosmic-applet-status-area/src/subscriptions/status_notifier_item.rs

https://github.com/pop-os/cosmic-applets/issues/165 should be fixed now. The apps I've tested all seem to display now.

Fix status-area with more clients; hide keyboard backlight when not present

---

cosmic-applet-time/src/window.rs
cosmic-applet-workspaces/src/components/app.rs
cosmic-panel-button/src/main.rs

also uses icons for panel buttons in vertical layout.

fix: better button sizing so there are no gaps

---

Cargo.lock
cosmic-app-list/Cargo.toml
cosmic-app-list/src/app.rs
cosmic-app-list/src/wayland_handler.rs
cosmic-app-list/src/wayland_subscription.rs

[figma designs from pop-os/ux](https://www.figma.com/proto/4USmAaMoDyYYPzfxlhXV0M/Dock-%26-Top-Panel?type=design&node-id=5397-68706&t=iaeKHoZXAN4GCQfk-1&scaling=contain&page-id=5304%3A62399&starting-point-node-id=5397%3A68706&mode=design)
to-do:

app-list: implement active toplevel click behavior

---

cosmic-app-list/src/app.rs
cosmic-app-list/src/wayland_handler.rs

This PR sets the selected property of the app-list buttons depending on whether the app is focused or not.
The PR also includes a fix to make tracking the focused app more robust.
Note: until the applet button has a separate look for "selected", the button will look the same

feat: Set focused window as selected

---

cosmic-applet-time/src/config.rs
cosmic-applet-time/src/lib.rs
cosmic-applet-time/src/window.rs

Implement military_time, show_date_in_top_panel and first_day_of_week configs.

feat(time): Implement time format configuration

---

cosmic-app-list/src/app.rs

cc: @git-f0x 
This PR allows people to middle click an app button in the app-list to launch a new window of the app.

feat: middle click app button to launch new window

---

Cargo.lock
cosmic-applet-workspaces/src/components/app.rs

fixes: https://github.com/pop-os/cosmic-applets/issues/338
cc @jackpot51 
I've noticed that workspaces is still very buggy, so this might be too early to make workspaces this accessible, but idk

workspaces: click active workspace to open overview

---

cosmic-applet-audio/src/lib.rs

Fixes https://github.com/pop-os/cosmic-applets/issues/335.
This calculates volume as a percentage of `Volume::NORMAL`, which seems to be the correct way to display PulseAudio volumes to the user. This matches `cosmic-osd`, and seems to match alsamixer.

audio: Don't use linear volume

---

cosmic-applet-network/src/app.rs
cosmic-applet-network/src/network_manager/mod.rs

I've tested this now and the previous changes work for connecting to networks that don't require a psk, but there was a bit more that could be done to clean up.

Network fix add connection

---

cosmic-applet-battery/src/backend/mod.rs

Fixes cosmic-applet-battery eating up CPU and spamming logs millions of times per second after #351 (cc @ryanabx) if both system76-power and power-profiles-daemon are not present (or at least cannot be connected to)
(The not-being-able-to-connect seems to be the case with system76-power, since there is no dbus policy that allows calls to `/com/system76/PowerDaemon:com.system76.PowerDaemon.GetProfile` from unprivileged users, as far as I can see in the upstream system76-power repo?)
Fixes lilyinstarlight/nixos-cosmic#73

battery: Give up if both power-profiles-daemon and system76-power connections fail

---

cosmic-applet-battery/i18n/id/cosmic_applet_battery.ftl

This pull request introduces Indonesian translations for essential terms used within the battery applets interface. These translations aim to improve the accessibility and usability of battery management features for Indonesian-speaking users.

feat(i18n): Add Indonesian translations for battery applet

---

cosmic-applet-workspaces/i18n/pl/cosmic_applet_workspaces.ftl

Changed verbiage for consistency with other parts of translation

Update cosmic_applet_workspaces.ftl PL Translation

---

cosmic-applet-battery/src/app.rs
cosmic-applet-battery/src/upower_device.rs
cosmic-applet-network/src/app.rs
cosmic-applet-notifications/src/lib.rs

fixes #384, #391, #389, and #383

fix(battery): exit when there is no battery detected

---

cosmic-applet-tiling/src/window.rs

refactor(tiling): remove tile windows on workspaces

---

cosmic-applet-audio/data/com.system76.CosmicAppletAudio.desktop
cosmic-applet-battery/data/com.system76.CosmicAppletBattery.desktop
cosmic-applet-bluetooth/data/com.system76.CosmicAppletBluetooth.desktop
cosmic-applet-network/data/com.system76.CosmicAppletNetwork.desktop
cosmic-applet-notifications/data/com.system76.CosmicAppletNotifications.desktop
cosmic-applet-power/data/com.system76.CosmicAppletPower.desktop
cosmic-applet-tiling/data/com.system76.CosmicAppletTiling.desktop
cosmic-applet-time/data/com.system76.CosmicAppletTime.desktop

required for https://github.com/pop-os/cosmic-panel/pull/164

feat: add entry to applets that support popup switching on hover

---

cosmic-app-list/data/com.system76.CosmicAppList.desktop
cosmic-applet-audio/data/com.system76.CosmicAppletAudio.desktop
cosmic-applet-battery/data/com.system76.CosmicAppletBattery.desktop
cosmic-applet-bluetooth/data/com.system76.CosmicAppletBluetooth.desktop
cosmic-applet-minimize/data/com.system76.CosmicAppletMinimize.desktop
cosmic-applet-network/data/com.system76.CosmicAppletNetwork.desktop
cosmic-applet-notifications/data/com.system76.CosmicAppletNotifications.desktop
cosmic-applet-power/data/com.system76.CosmicAppletPower.desktop
cosmic-applet-status-area/data/com.system76.CosmicAppletStatusArea.desktop
cosmic-applet-tiling/data/com.system76.CosmicAppletTiling.desktop
cosmic-applet-time/data/com.system76.CosmicAppletTime.desktop
cosmic-applet-workspaces/data/com.system76.CosmicAppletWorkspaces.desktop
cosmic-panel-app-button/data/com.system76.CosmicPanelAppButton.desktop
cosmic-panel-launcher-button/data/com.system76.CosmicPanelLauncherButton.desktop
cosmic-panel-workspaces-button/data/com.system76.CosmicPanelWorkspacesButton.desktop

cleanup: applet names and comments

---

Cargo.lock
cosmic-applet-audio/src/lib.rs
cosmic-applet-status-area/data/com.system76.CosmicAppletStatusArea.desktop
cosmic-applet-status-area/src/components/app.rs

Also fixes audio applet panel playback button handling of auto-clicks from the panel.

Status Area applet list auto-popup on hover

---

cosmic-applet-battery/src/app.rs

fix(battery): trim gpu name

---

cosmic-applet-audio/data/com.system76.CosmicAppletAudio.desktop
cosmic-applet-audio/src/lib.rs
cosmic-applet-battery/data/com.system76.CosmicAppletBattery.desktop
cosmic-applet-bluetooth/data/com.system76.CosmicAppletBluetooth.desktop
cosmic-applet-input-sources/data/com.system76.CosmicAppletInputSources.desktop
cosmic-applet-network/data/com.system76.CosmicAppletNetwork.desktop
cosmic-applet-notifications/data/com.system76.CosmicAppletNotifications.desktop
cosmic-applet-power/data/com.system76.CosmicAppletPower.desktop
cosmic-applet-status-area/data/com.system76.CosmicAppletStatusArea.desktop
cosmic-applet-tiling/data/com.system76.CosmicAppletTiling.desktop
cosmic-applet-time/data/com.system76.CosmicAppletTime.desktop

should be a proper fix for #415

refactor: set locations of auto popup hover

---

cosmic-applet-status-area/src/components/app.rs

fixes https://github.com/pop-os/cosmic-applets/issues/315

fix(status-area): update existing menu if a duplicate is registered

---

cosmic-applet-tiling/src/window.rs

fix: force per-workspace setting

---

cosmic-applet-input-sources/src/window.rs

fix(input-sources): remove extra divider and button

---

Cargo.lock
cosmic-applet-time/src/window.rs
cosmic-applet-workspaces/src/components/app.rs
cosmic-panel-button/src/main.rs

Requires https://github.com/pop-os/libcosmic/pull/446

feat: applet text scaling based on panel size

---

cosmic-app-list/src/app.rs
cosmic-app-list/src/config.rs

fixes https://github.com/pop-os/cosmic-applets/issues/358

feat(app-tray): config option for dnd

---

Cargo.lock
cosmic-app-list/src/app.rs
cosmic-applet-audio/src/lib.rs
cosmic-applet-input-sources/src/window.rs
cosmic-applet-power/src/lib.rs
cosmic-applet-status-area/src/components/status_menu.rs
cosmic-applet-time/src/window.rs
cosmic-panel-button/src/main.rs

requires #265 first, or it could be merged instead.

Input text size

---

Cargo.lock
cosmic-panel-button/src/main.rs

Along with https://github.com/pop-os/cosmic-launcher/pull/129, this will fix #411

refactor: activate panel-button applet on press down

---

cosmic-applet-input-sources/src/lib.rs
cosmic-applet-input-sources/src/window.rs
cosmic-applet-tiling/src/wayland.rs
cosmic-applet-tiling/src/wayland_subscription.rs
cosmic-applet-tiling/src/window.rs

fixes https://github.com/pop-os/cosmic-applets/issues/331

fix: apply default behavior to workspaces which never had a toplevel

---

cosmic-app-list/i18n/de/cosmic_app_list.ftl
cosmic-app-list/i18n/en/cosmic_app_list.ftl
cosmic-app-list/i18n/es-ES/cosmic_app_list.ftl
cosmic-app-list/i18n/fa/cosmic_app_list.ftl
cosmic-app-list/i18n/fi/cosmic_app_list.ftl
cosmic-app-list/i18n/fr/cosmic_app_list.ftl
cosmic-app-list/i18n/it/cosmic_app_list.ftl
cosmic-app-list/i18n/ja/cosmic_app_list.ftl
cosmic-app-list/i18n/ko/cosmic_app_list.ftl
cosmic-app-list/i18n/nl/cosmic_app_list.ftl
cosmic-app-list/i18n/pl/cosmic_app_list.ftl
cosmic-app-list/i18n/pt-BR/cosmic_app_list.ftl
cosmic-app-list/i18n/pt/cosmic_app_list.ftl
cosmic-app-list/i18n/ru/cosmic_app_list.ftl
cosmic-app-list/i18n/sr-Cyrl/cosmic_app_list.ftl
cosmic-app-list/i18n/sr-Latn/cosmic_app_list.ftl
cosmic-app-list/src/app.rs
cosmic-app-list/src/config.rs
cosmic-app-list/src/utils.rs

Closes #457.
Didn't change the references in code, since something like Pin and UnPin could be potentially ambiguous. Just changed the Fluent string (the translator-facing part).

[App Tray] Change favorite/un-favorite to pin/unpin

---

cosmic-app-list/i18n/tr/cosmic_app_list.ftl

#466 got merged before i was able to do this change sorry about that. This change is due to #461.

i81n(tr): changing favorite and unfavorite to pin and unpin

---

Cargo.lock
Cargo.toml
cosmic-app-list/Cargo.toml
cosmic-app-list/src/app.rs
cosmic-app-list/src/config.rs

fix #464 and hopefully #468.
Depend on https://github.com/pop-os/libcosmic/pull/481

fix: app-list icons

---

cosmic-applet-power/i18n/pl/cosmic_applet_power.ftl

There is no pl translation yet, i figured out it might be handy

Create cosmic_applet_power.ftl PL translation

---

cosmic-applet-network/i18n/pl/cosmic_applet_network.ftl

Update cosmic_applet_network.ftl PL translation

---

cosmic-applet-audio/src/lib.rs
cosmic-applet-audio/src/mouse_area.rs

It works great on my machine and for my touch pad 40.3125 is ideal.

scroll audio icon to apply volume changes

---

cosmic-applet-audio/src/lib.rs

fix: click on open setting button doesn't open COSMIC Settings

---

cosmic-applet-power/src/lib.rs

Fix for https://github.com/pop-os/cosmic-applets/issues/532
In my case there were two sessions. The first session did not have a class (or at least, it failed to be retrieved). The second session was the `User` session, the one that should be locked. Attempting to lock the first session fails, causing the loop to terminate, meaning the second session was never requested to lock. The error while locking the first session was:
> cosmic-applet-power ERROR: 'org.freedesktop.DBus.Error.NotSupported: Session does not support lock screen.'
This most likely also fixes https://github.com/pop-os/cosmic-greeter/issues/72 , which is probably the same issue. The reason locking sometimes works is presumably due to the order of the sessions. If the `User` session is first in the list, then it locks …

Lock only User sessions.

---

cosmic-applet-power/i18n/pl/cosmic_applet_power.ftl

Update cosmic_applet_power.ftl PL translation

---

cosmic-applet-notifications/i18n/pl/cosmic_applet_notifications.ftl

Update cosmic_applet_notifications.ftl PL translation

---

cosmic-applet-minimize/src/lib.rs
cosmic-applet-status-area/src/components/app.rs

Hi!
Forgotten leftovers from #568 
Thanks!

fix: make overflow button and status area buttons popup on press down

---

cosmic-applet-time/src/window.rs

Hi again! My last patch had a regression where the stream would spam updates. :scream_cat:  I fixed it in this patch as well as vastly simplified my code too.
Closes: #603, #607

regression: Timezone stream spams updates

---

cosmic-applet-battery/src/app.rs

fix battery percent

---

cosmic-applet-time/src/window.rs

fix https://github.com/pop-os/cosmic-applets/issues/641

fix: time applet

---

cosmic-applet-battery/src/app.rs
cosmic-applet-battery/src/backend/mod.rs

Hi,
Simple implementation of setting charging limit via system76 power daemon. I noticed it does not work right now at all, so I think it would be nice to bring this ability to work. Not sure how good it is, but it should works as expected. If there won't find s76 power daemon or setting will not success it simply should leave toggle as unchecked.

set charging limit via s76 power daemon

---

cosmic-applet-audio/src/pulse.rs

fix: audio applet hight CPU

---

cosmic-applet-audio/src/lib.rs
cosmic-applet-audio/src/pulse.rs

Debounces slider messages so that they're applied at 64ms intervals. Reduces CPU usage by half

perf(audio): further reduce CPU usage

---

debian/control

Part of https://github.com/pop-os/system76-driver/pull/305

Provide system76-power-applet-virtual

---

Cargo.lock
cosmic-applet-power/src/lib.rs

should fix memory leak and high CPU in certain situations with autosize popups./
fixes #714 & https://github.com/pop-os/cosmic-panel/issues/288

fix: update libcosmic

---

Cargo.lock
Cargo.toml
cosmic-applet-notifications/src/lib.rs
cosmic-applet-notifications/src/subscriptions/notifications.rs

can be tested with https://github.com/pop-os/cosmic-notifications/pull/57

feat: notification actions

---

cosmic-applet-time/src/window.rs

fix(time): Update calendar on timezone change

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
cosmic-app-list/src/app.rs
cosmic-app-list/src/wayland_handler.rs
cosmic-applet-minimize/src/wayland_handler.rs

Requires https://github.com/pop-os/cosmic-protocols/pull/46.

Use updated screencopy abstraction

---

cosmic-applet-bluetooth/src/app.rs
cosmic-applet-bluetooth/src/bluetooth.rs

Follow up PR for https://github.com/pop-os/cosmic-settings/pull/952.

improve(bluetooth): ignore devices with unknown type and without alias

---

cosmic-applet-power/i18n/sv/cosmic_applet_power.ftl

This adds a swedish translation for the power applet

Add swedish translation for power applet

---

cosmic-applet-audio/src/pulse.rs

should fix https://github.com/pop-os/cosmic-applets/issues/788

fix(audio): delay retries

---

cosmic-applet-bluetooth/src/bluetooth.rs

fixes https://github.com/pop-os/cosmic-applets/issues/640

fix(bluetooth): watch devices for changes after toggled back on

---

cosmic-applet-bluetooth/src/bluetooth.rs

this state will be persisted after reboot
fixes https://github.com/pop-os/cosmic-applets/issues/430.
Cosmic settings should probably also be updated to use rfkill

fix(bluetooth): use rfkill for blocking bluetooth

---

cosmic-applet-time/src/window.rs

The 'Standard' ButtonStyle seemed made for this enhancement request: https://github.com/pop-os/cosmic-applets/issues/844
The current day will be highlighted in the Standard style if another date is selected. Otherwise it will keep the default highlight as it does currently.

feat: date applet - add highlight for current day

---

cosmic-applet-a11y/i18n/pl/cosmic_applet_a11y.ftl

Create cosmic_applet_a11y.ftl PL initial

---

cosmic-applet-status-area/src/components/status_menu.rs
cosmic-applet-status-area/src/subscriptions/status_notifier_item.rs

It seems status icons, at least some, don't send property change notifications. So we can't rely on that, and have to disable caching. And handle the `NewIcon` signal defined in
https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem
I'm not sure whether or not there's a *good* reason it works this way, but regardless I see `nm-applet` and `ibus` update their icons as they should after these changes.

status-area: Handle changes to icon properties

---

cosmic-applet-bluetooth/src/bluetooth.rs

fix(bluetooth): await sleep

---

Cargo.lock
cosmic-applet-a11y/i18n/en/cosmic_applet_a11y.ftl
cosmic-applet-a11y/src/app.rs
cosmic-applet-a11y/src/backend/wayland/mod.rs
cosmic-applet-a11y/src/backend/wayland/thread.rs

~~Draft while https://github.com/pop-os/cosmic-protocols/pull/56 isn't merged.~~
Can be merged without cosmic-comp support.

a11y: screen filters

---

cosmic-applet-power/src/lib.rs

refactor(power): remove text from icons

---

cosmic-applet-network/i18n/en/cosmic_applet_network.ftl
cosmic-applet-network/src/app.rs
cosmic-applet-network/src/network_manager/available_wifi.rs
cosmic-applet-network/src/network_manager/mod.rs

follow up for https://github.com/pop-os/cosmic-applets/pull/232. This would fix https://github.com/pop-os/cosmic-applets/issues/225. I need to find a network to test this on, but it should work.

feat(network): support for eap peap networks

---

cosmic-applet-a11y/i18n/ga/cosmic_applet_a11y.ftl

Updated Irish translation

---

Cargo.lock
Cargo.toml
cosmic-applet-time/Cargo.toml
cosmic-applet-time/src/config.rs
cosmic-applets-config/Cargo.toml
cosmic-applets-config/src/lib.rs

This is to support https://github.com/pop-os/cosmic-greeter/pull/237

Expose applet configs, starting with time applet

---

cosmic-applet-network/i18n/pl/cosmic_applet_network.ftl

Update cosmic_applet_network.ftl PL Translation identity network

---

flake.lock
flake.nix

updates and fixes the broken flake.nix 

---

Cargo.lock
cosmic-app-list/src/app.rs

fixes https://github.com/pop-os/cosmic-applets/issues/888

App tray DnD fix

---

cosmic-applet-audio/src/lib.rs

For example, when using volume keys.

Update volume sliders when volume changes externally

---

Cargo.lock
cosmic-app-list/src/app.rs

Depends-on: https://github.com/pop-os/libcosmic/pull/880
Depends-on: https://github.com/pop-os/cosmic-panel/pull/396
See https://github.com/pop-os/cosmic-panel/pull/396 for more information!

Handle custom panel sizes in cosmic-app-list

---

Cargo.lock
cosmic-applet-time/Cargo.toml
cosmic-applet-time/src/window.rs

Update time in time applet when resuming from sleep

---

cosmic-applet-bluetooth/src/bluetooth.rs

fix(bluetooth): typo

---

Cargo.lock
cosmic-applet-a11y/Cargo.toml
cosmic-applet-audio/Cargo.toml
cosmic-applet-battery/Cargo.toml
cosmic-applet-battery/src/app.rs
cosmic-applet-battery/src/backend/mod.rs

fix for #412 & #413. Support for more devices in system76-power can definitely be improved, but I believe these issues probably only occur on unsupported devices.

Hide unsupported charge limit

---

cosmic-applet-bluetooth/src/bluetooth.rs
cosmic-applet-network/src/network_manager/mod.rs

This makes the network applet work on Debian, for instance.
It may be better to directly use `/dev/rfkill`, but this improves things for now.

Fix calls to `rfkill` on distros that put in in `sbin`

---

Cargo.lock
Cargo.toml
cosmic-applet-time/Cargo.toml
cosmic-applet-time/src/time.rs
cosmic-applet-time/src/window.rs

`Locale::default()` doesn't exist with 2.0.0, so some more advanced locale handling was added.

refactor(time): update to icu 2.0.0
