pop-os/cosmic-applets

- Cargo.toml
This reduces total package size by ~25%. There are no runtime consequences, though this does nearly double build times. But with the cargo workspace, this repo builds pretty quick. As well the same `lto` settings are already used in cosmic-comp.
> Use linker time optimization for release builds

- cosmic-applet-battery/src/app.rs
- cosmic-applet-battery/src/backlight.rs
- cosmic-applet-battery/src/upower_kbdbacklight.rs
This fixes a couple issues with the battery applet.
- screen brightness slider can go too low, causing a black screen
- keyboard brightness read value was too high
> Fix battery jammy

- cosmic-applet-power/src/main.rs
The horizontal rule widget is problematic for auto-sized popups. Ideally there would be a divider which fills out to the same width as the other widgets in its parent, but not any further. Maybe, for example, a container which contains optional rule widgets on the top or bottom and sets them to the width of it's contents would be a good solution.
In any case, for now, I've increased the size limit of the popup here to fit the English text, but I'll also work on a solution via libcosmic.
> fix: increase popup size limits to fix text for each button

- cosmic-applet-network/Cargo.toml
I was getting 
```
warning: /home/ron/GitHub/pop-os/cosmic-epoch/cosmic-applets/cosmic-applet-network/Cargo.toml: unused manifest key: dependencies.zbus.no-default-features
```
After reading https://doc.rust-lang.org/cargo/reference/features.html?highlight=no-default-features#the-default-feature I believe this PR is how default features should be disabled
> fix: disable default-features for zbus

- Cargo.lock
- cosmic-app-list/src/app.rs
- cosmic-applet-graphics/src/main.rs
- cosmic-applet-network/src/app.rs
- cosmic-applet-time/src/main.rs
- cosmic-applet-workspaces/src/components/app.rs
This updates libcosmic so that the applets use dyrend.
Currently it works quite well except when the app-list shrinks in size, there is visual corruption. Perhaps it is an issue with iced-sctk.
> feat: update libcosmic to use dyrend

- cosmic-app-list/src/app.rs
Specific case when using vscode, the open file/folder dialog doesn't succeed in looking up the icon on my system. This would cause lookup to return None, thus the ret vector is empty. Since we removed the id before the lookup, the append below would append an empty vec. This would cause an error in AddTopLevel message handler when trying to remove the first item of the returned vec.
Move the id remove directly within the map, so it only gets removed if we succeed in looking up the icon.
> fix: crash when no icon found

- cosmic-applet-network/src/app.rs
- cosmic-applet-network/src/network_manager/available_wifi.rs
- cosmic-applet-network/src/network_manager/current_networks.rs
- cosmic-applet-network/src/network_manager/mod.rs
This improves some of the state handling. Specifically, when an action was finished, the loading icon didn't always go away before, or for some items, it didn't appear at all. Also, the option to disconnect networks has been added as indicated the mockup.
The applet could probably be cleaned up more in the future, but I might improve the dbus bindings before doing that.
> feat(network): improve state handling & add disconnect option

- justfile
Just doesn't have arrays or and currently lacks new line escapes, so this seems like the best way to do things for now.
> justfile: Use recipe parameters to reduce duplication

- Cargo.lock
- cosmic-app-list/src/toplevel_handler.rs
- cosmic-applet-audio/Cargo.toml
- cosmic-applet-battery/Cargo.toml
- cosmic-applet-battery/src/app.rs
- cosmic-applet-bluetooth/Cargo.toml
- cosmic-applet-bluetooth/src/app.rs
- cosmic-applet-graphics/Cargo.toml
- cosmic-applet-network/Cargo.toml
- cosmic-applet-network/src/app.rs
- cosmic-applet-notifications/src/main.rs
- cosmic-applet-power/Cargo.toml
- cosmic-applet-power/src/main.rs
- cosmic-applet-workspaces/Cargo.toml
- cosmic-applet-workspaces/src/wayland.rs
Depends on https://github.com/pop-os/iced/pull/33, https://github.com/pop-os/libcosmic/pull/87 and https://github.com/pop-os/cosmic-protocols/pull/16. Then this can be updated to remove the `[patch]` sections.
> Update sctk, libcosmic, cosmic-client-toolkit

- Cargo.lock
- cosmic-app-list/Cargo.toml
- cosmic-app-list/src/app.rs
Drag and drop support in app list. It won't start working inside the panel until i set up xdg-shell-wrapper support again, but the applet works pretty well running in cosmic-comp.
I will probably do a bit more polishing though. For example, it is currently possible to empty the favorites list and not have any space to drag new favorites to, so I need to provide space on drag in the case of an empty list.
> App list dnd jammy

- cosmic-app-list/data/com.system76.CosmicAppList.desktop
- cosmic-app-list/data/com.system76.CosmicAppList.metainfo.xml
- cosmic-applet-audio/data/com.system76.CosmicAppletAudio.desktop
- cosmic-applet-battery/data/com.system76.CosmicAppletBattery.desktop
- cosmic-applet-bluetooth/data/com.system76.CosmicAppletBluetooth.desktop
- cosmic-applet-graphics/data/com.system76.CosmicAppletGraphics.desktop
- cosmic-applet-network/data/com.system76.CosmicAppletNetwork.desktop
- cosmic-applet-notifications/data/com.system76.CosmicAppletNotifications.desktop
- cosmic-applet-power/data/com.system76.CosmicAppletPower.desktop
- cosmic-applet-time/data/com.system76.CosmicAppletTime.desktop
- cosmic-applet-workspaces/data/com.system76.CosmicAppletWorkspaces.desktop
- cosmic-panel-app-button/data/com.system76.CosmicPanelAppButton.desktop
- cosmic-panel-workspaces-button/data/com.system76.CosmicPanelWorkspacesButton.desktop
the applet key marks an application as possible to be used as an applet
> chore: add applet key and do some cleanup

- Cargo.lock
- Cargo.toml
- applet/Cargo.toml
- cosmic-app-list/Cargo.toml
- cosmic-app-list/src/app.rs
- cosmic-applet-audio/Cargo.toml
- cosmic-applet-battery/Cargo.toml
- cosmic-applet-bluetooth/Cargo.toml
- cosmic-applet-graphics/Cargo.toml
- cosmic-applet-network/Cargo.toml
- cosmic-applet-notifications/Cargo.toml
- cosmic-applet-power/Cargo.toml
- cosmic-applet-time/Cargo.toml
- cosmic-applet-workspaces/Cargo.toml
- cosmic-applet-workspaces/src/wayland.rs
- cosmic-panel-button/Cargo.toml
Using `[workspace.dependencies]`, we can update `rev =` for a dependency in one place, instead of each individual applet.
> Update dependencies, and use workspace dependencies

- justfile
This variable was defined, but never used, and "release" was hardcoded instead.
> justfile: respect target variable

- cosmic-app-list/src/app.rs
Also fixes the default icon. `application-default` is a name given by the Pop-icon-theme. `application-x-executable`  is used as an additional fallback. That is a freedesktop standard icon name, but not included in the usual `hicolor`-theme, which `freedesktop-icons` searches by default. So lets explicitly link the `default` theme, which should link to user-preference.
> app-list: Match by startup WM Class for Xwayland compatibility

- cosmic-app-list/src/app.rs
Quick follow up PR to https://github.com/pop-os/cosmic-applets/pull/123.
`application-default` is also in the `Cosmic`, which is probably what we want here, given it is also the default for libcosmic and falls back to `Pop` anyway.
Additionally, given we control this theme and know it's contents, force the svg variant instead of a specific size for a cleaner look.
> app-list: Use cosmic theme instead of pop

- Cargo.lock
- cosmic-applet-workspaces/src/components/app.rs
Redesign of the workspaces applet based on issac's last iteration and @maria-komarova's feedback and changes.
https://www.figma.com/file/fJ9QmTUhtV9ytSFCF3mvi8/Workspace-Switcher-Panel-Applet?type=design&node-id=414-542&mode=design&t=nxurraRJJPG1q3Og-0
Code has been cleaned up, this is the only case so far, where we needed a Bold font variant. Should this be added to libcosmic or does that not warrant pre-loading for every single app?
Any other suggestions to make the style code more concise? Essentially the Urgent and Normal modes are Text-Buttons with custom Text colors, but I didn't find a better way to express this.
> workspaces: Cleaner design

- Cargo.lock
- cosmic-applet-time/src/window.rs
This adds a custom container which ignores the layout bounds it is provided. Maybe this could be made an optional part of the `RectangleTracker` instead?
> fix(time): layout should ignore the current bounds of the window

- cosmic-applet-network/i18n/en/cosmic_applet_network.ftl
Currently when airplane mode is **on** the message states "Turn on to enable Wi-Fi..." instead of "Turn off...", which seems to be the intended meaning.
> Fix airplane mode text in cosmic-applet-network

- cosmic-applet-power/src/main.rs
Not sure if this is all that needs to be done, but I haven't been able to find anything else that relates to the suspend icon. If this is intended temporarily (since the icon was a crescent moon at some point, and now is the same as the lock screen icon), feel free to close the pull request. :)
> Fix suspend icon in cosmic-applet-power

- cosmic-applet-audio/src/mpris_subscription.rs
This is on top of the updates from earlier
> Fix mpris jammy

- cosmic-applet-graphics/src/window.rs
should fix #173. This makes the button press-able if the graphics can be switched.
> fix(graphics): only show the button if the graphics can be switched

- cosmic-applet-workspaces/src/wayland.rs
> fix: workspaces scrolling

- cosmic-applet-network/src/app.rs
- cosmic-applet-network/src/network_manager/mod.rs
I need to do some more testing of this to make sure it works as intended.
> fix(network): open a browser when connection is behind a captive portal

- cosmic-applet-battery/src/dgpu.rs
Handles hotplug events more reliably/quicker and seems to prevent the applet state freezing.
> battery: Re-evaluate gpu state on udev change event

- Cargo.lock
- Cargo.toml
without this feature, it defaults to info, and with the feature it uses the variable, but falls back to error.
> fix: enable env-filter feature for tracing subscriber

- Cargo.lock
- cosmic-applet-tiling/Cargo.toml
this seems to resolve recent performance issues for the panel. #239
> fix: disable wgpu feature for tiling applet

- cosmic-app-list/src/app.rs
Potential solution for:
https://github.com/pop-os/cosmic-applets/issues/222
Fixes:
https://github.com/pop-os/cosmic-panel/issues/101
* Reduced width padding to 1, length padding remains at 8
* Reduced the spacing between the dot and icon in an app icon button to 1
* Increased the size of the app's icon by 8
* App icons for closed apps will now align with app icons for opened apps
* The panel at smaller sizes will no longer need to resize itself to be larger when the app list applet is loaded in 
* Basically if no apps were open, the sizing would be fine, but if an app was open, the panel would have to resize itself to make room for the dot and all the padding.
| With the PR | Without the PR |
| --- | --- |
| ![screenshot-2024-03-03-06-28-19](https://github.com/pop-os/cosmic-applets/assets/ …
> app-list (RFC): make app list icons more visible at smaller panel sizes (and some various fixes)

- cosmic-applet-tiling/src/wayland.rs
- cosmic-applet-workspaces/src/wayland.rs
This should help lower cpu usage of the workspaces applet and tiling applet
> refactor: set dispatch to None for tiling and workspaces

- Cargo.lock
- cosmic-app-list/src/app.rs
Requires: https://github.com/pop-os/libcosmic/pull/341
Fixes: https://github.com/pop-os/cosmic-applets/issues/278
Make sure to bump libcosmic and merge the required libcosmic PR above before merging this!
This fixes the issue described in #278
> fix: app list doesn't match fallback apps with their favorited entry

- justfile
resolves #289 also has the side effect of allowing to set `prefixdir=` allowing for non `/bin` folders if wanted
> fix(justfile): add prefixdir for symlink

- cosmic-app-list/data/com.system76.CosmicAppList.desktop
- cosmic-applet-minimize/data/com.system76.CosmicAppletMinimize.desktop
Now that https://github.com/pop-os/cosmic-panel/commit/6590999f80459726bf026a4529711be7af8eb316 is merged, we should set integer priorities for the X-MinimizeApplet entry in the cosmic-applet-minimize .desktop file. Additionally, we can now make cosmic-app-list a 'fallback' minimize applet when cosmic-applet-minimize isn't present.
Future work:
In addition to this, I can make a 2nd PR which will let cosmic-applet-minimize gracefully exit with no errors if it is not chosen as the minimize applet (this would only happen if someone were to make a 3rd party minimize applet with higher priority than the 1st party one)
> feat: set integer X-MinimizeApplet priorities

- Cargo.lock
- cosmic-applet-status-area/src/components/app.rs
- cosmic-applet-status-area/src/components/status_menu.rs
- cosmic-applet-status-area/src/subscriptions/status_notifier_item.rs
This is at least one of the issue behind
https://github.com/pop-os/cosmic-applets/issues/165. OBS now shows it's icon instead of an empty space. But the Mattermost flatpak doesn't show anything. (Is that Flatpak related, or does it not use `StatusNotifierItem`?)
Requires https://github.com/pop-os/libcosmic/pull/368. Ideally, it should have some way to choose from multiple icons in memory of different sizes.
> status-area: Show icons that have `icon_pixmap` but not `icon_name`

- cosmic-app-list/src/app.rs
- cosmic-app-list/src/wayland_handler.rs
- cosmic-app-list/src/wayland_subscription.rs
This PR lessens the use of screencopy in my recent app-list PR, by only requesting window captures once the popup is triggered and when the toplevel first exists.
The previous method (whenever a TopLevelUpdate occurs) sacrifices performance for no reason, since the images aren't needed every update, and also means we don't always get a toplevel update between checking the popup (for example, scroll on an app without changing anything else about the window, the image won't update)
The caveat with this method is that there will be a small period of time where the previous screencopy is used on the popup, then the new image will take its place once its ready. That time will depend on the speed of the computer, but for my debug build it was a noticeable amount of time, less than half a second …
> improv(app-list): only send screencopy requests as needed

- cosmic-app-list/src/app.rs
- cosmic-app-list/src/wayland_handler.rs
- cosmic-app-list/src/wayland_subscription.rs
There have been numerous reports of compositor crashes following this PR https://github.com/pop-os/cosmic-applets/pull/317.
https://matrix.to/#/!u3Y5dwYi8p48iq7tiq:conduit.rs/$fmkBSi_d0QRuu5drcvDkB_-vZnxlzXnfUl6LpHp3J94?via=nixos.org&via=matrix.org&via=beeper.com
https://github.com/ublue-os/cosmic/issues/22
I also have gotten my own crashes, in particular one from firefox, which caused a spiral of crashes.
This pr: https://github.com/pop-os/cosmic-applets/pull/322 lessened the amount of screencopy requests we are making by a lot, which should mitigate the issue. I think the bug reports from users are people using the previous commit, but I'm not fully satisfied with just doing that. I'd like to use this as an opportunity to harden the wayland handler implementation as much as we can.
I've …
> app-list/applet-minimize: stability fixes

- Cargo.lock
- cosmic-applet-audio/src/lib.rs
- cosmic-applet-audio/src/mpris_subscription.rs
- cosmic-applet-audio/src/pulse.rs
- cosmic-applet-status-area/src/components/app.rs
Changing the volume now sets PulseAudio mute state (https://github.com/pop-os/cosmic-applets/issues/234), and the icons are adjusted to use the correct icon for each level. The behavior should match Gnome now.
This overhauls the mpris2 logic to avoid creating multiple proxies and streams, which fixes https://github.com/pop-os/cosmic-applets/issues/306 and should perform better.
The status area applet now handles vertical panels (https://github.com/pop-os/cosmic-applets/issues/314).
> Improve audio applet, and support vertical panel in status area applet

- cosmic-applet-audio/src/lib.rs
- cosmic-applet-audio/src/mpris_subscription.rs
- cosmic-applet-audio/src/pulse.rs
The panel buttons for next/previous didn't do anything since `on_press` wasn't set. Now they work.
Fixed `autosize` which I had accidentally committed after using it for testing. (It would be good to figure out why the applets don't work properly with autosize when run outside of the panel, since that's handy for testing.)
I noticed with VLC, skipping a track makes the media controls disappear very briefly, and sometimes the pause button didn't return. I guess `can_play` (etc.) are temporarily set to false, probably expecting the controls to be greyed out and not hidden from a panel. Anyway, monitoring for changes to these properties as well will hopefully fix the part where it could remain missing. Though I can't reproduce that consistently.
> audio: Mpris media control fixes

- cosmic-applet-network/src/app.rs
- cosmic-applet-network/src/network_manager/available_wifi.rs
- cosmic-applet-network/src/network_manager/mod.rs
This cleans up the existing code for connecting to wifi. It also hopefully fixes an issue where connections couldn't be made with networks that don't have a password. Now, if a connection doesn't exist when an access point is selected, it will be created. I hope to test that this resolves that issue soon.
> fix(network): add connection if it doesn't exist when it is selected

- cosmic-applet-audio/i18n/id/cosmic_applet_audio.ftl
This PR adds Indonesian translations for key terms used within the Linux sound applets interface. These translations are aimed at improving the accessibility and usability of sound management features for Indonesian-speaking users.
> feat(i18n): Add Indonesian translations for sound applet

- cosmic-applet-status-area/src/components/app.rs
> fix(status-area): force size to match symbolic icons

- cosmic-applet-bluetooth/i18n/id/cosmic_applet_bluetooth.ftl
This PR introduces Indonesian translations for essential terms used within the Bluetooth applets interface. These translations are designed to enhance the accessibility and usability of Bluetooth management features for Indonesian-speaking users.
> feat(i18n): Add Indonesian translations for bluetooth applet 

- Cargo.lock
- Cargo.toml
- cosmic-panel-button/Cargo.toml
- cosmic-panel-button/src/config.rs
- cosmic-panel-button/src/main.rs
This PR adds an optional environment variable to the cosmic-panel-button that allows us to specify how a panel button should present itself (either as 'icon' or as 'text').
This is before I add any overrides:
This is after overriding the presentation of the launcher button and the workspaces button to be an icon, even though this is a horizontal panel:
This enables us in the future to expose an option in cosmic-settings to force an icon or text in a panel button, if we so choose. Otherwise, it can remain a niche configuration option.
Discussion: This option could also be presented as a command line argument instead of an environment variable. I chose an environment variable because it makes more sense for when there could be many different configuration options for an applet, to simply …
> feat(panel-button): add cosmic config for panel button

- cosmic-app-list/data/icons/scalable/apps/com.system76.CosmicAppList.svg
- cosmic-applet-status-area/data/icons/scalable/apps/com.system76.CosmicAppletStatusArea.svg
- cosmic-panel-app-button/data/icons/scalable/apps/com.system76.CosmicPanelAppButton.svg
- cosmic-panel-launcher-button/data/icons/scalable/apps/com.system76.CosmicPanelLauncherButton.svg
- cosmic-panel-workspaces-button/data/icons/scalable/apps/com.system76.CosmicPanelWorkspacesButton.svg
Updated: App Tray, Notifications Tray and all panel button applets.
Tried adding the Input Sources icon, but the preview just showed the code, and not the icon.
Not sure how to have the tiling applet icon show up in Settings.
There may have to be some changes in Settings, so that the colored icons can be visible.
> Update applet icons

- Cargo.lock
- Cargo.toml
- cosmic-applet-network/Cargo.toml
- cosmic-applet-network/i18n/en/cosmic_applet_network.ftl
- cosmic-applet-network/src/app.rs
- cosmic-applet-network/src/network_manager/mod.rs
also updates libcosmic and cosmic-protocolss, and adds clipboard support to the network applet. It should generally improve the applet reliability as well.
> fix: allow network resets

- cosmic-applet-status-area/src/components/app.rs
- cosmic-applet-status-area/src/components/status_menu.rs
- cosmic-applet-status-area/src/subscriptions/status_notifier_item.rs
- cosmic-applet-status-area/src/subscriptions/status_notifier_watcher/server.rs
This fixes Slack, and probably some other applications.
Dropbox still doesn't seem to work. `gnome-shell-extension-appindicator` has three different comments about Dropbox, so it seems to be notorious about doing things wrong and may need special workarounds.
> Fixes for Status Area applet

- cosmic-panel-button/src/main.rs
This makes text panel buttons slightly less condensed and increases the distance between the text of the button and panel edges.
> [Panel button] Add text button horizontal padding

- cosmic-app-list/data/default_schema/com.system76.CosmicAppList/v1/favorites
This adds COSMIC Store to the default configuration, which should complete the App Tray portion of pop-os/iso#332.
> [App Tray] Update defaults

- cosmic-applet-audio/src/lib.rs
- cosmic-applet-audio/src/pulse.rs
Recently a change was made to update the audio applet icons when the volume changes by an action from outside the applet, but the volume sliders still didn't update.
So for example, if you have the audio applet open, and use media keys on your keyboard to change the volume, the volume sliders will now update in the applet to reflect the change.
This also adds the ability to mute/unmute by clicking on the icons left of the volume sliders. I was going to implement this in a separate PR, but it relies on the other changes.
> Update volume sliders when changing volume with media keys

- cosmic-app-list/src/app.rs
This adds some padding to the divider between pinned and unpinned apps in the App Tray, to match the designs.
The change for the context menu horizontal padding is to match other context menus, and some examples from the designs.
I experimented with adding some padding to the context menu dividers, but since the styling of the App Tray context menu doesn't match other context menus (menus in apps have a lighter background color and slightly rounded selection highlights), it would need excessive vertical padding to look good.
> [App Tray] Add padding to unpinned app divider

- Cargo.lock
- cosmic-app-list/src/app.rs
- cosmic-app-list/src/wayland_handler.rs
- cosmic-app-list/src/wayland_subscription.rs
- cosmic-applet-audio/src/lib.rs
- cosmic-applet-battery/src/app.rs
- cosmic-applet-bluetooth/src/app.rs
- cosmic-applet-input-sources/src/window.rs
- cosmic-applet-network/src/app.rs
- cosmic-applet-network/src/network_manager/mod.rs
- cosmic-applet-notifications/src/lib.rs
- cosmic-applet-power/src/lib.rs
- cosmic-applet-time/src/window.rs
Allows `xdg-desktop-portal` to get app id from PID.
Depends on https://github.com/pop-os/libcosmic/pull/548.
> Update for `spawn_desktop_exec` that calls `SpawnTransientUnit`

- cosmic-applet-power/src/lib.rs
This makes the button have a highlight on hover.
> Use text button for Restart in Shutdown dialog

- cosmic-applet-audio/src/lib.rs
The original padding was 0, but 4 looks closer to the designs, while not leaving too much unclickable space.
The commit message should say audio instead of sound.
> [Audio] Add settings button

- cosmic-applet-audio/src/lib.rs
- rust-toolchain.toml
There could be improvements to the size calculation for the text widget, but this is a fix that prevents overlap. fixes #569
> fix(audio): rtl media title overlap on controls

- cosmic-applet-audio/src/lib.rs
- cosmic-applet-battery/src/app.rs
- cosmic-applet-bluetooth/src/app.rs
- cosmic-applet-input-sources/src/window.rs
- cosmic-applet-network/src/app.rs
- cosmic-applet-notifications/src/lib.rs
- cosmic-applet-power/src/lib.rs
- cosmic-applet-tiling/src/window.rs
- cosmic-applet-time/src/window.rs
Hi!
This PR simply makes the applets toggle their popup on button pressdown instead of on button release. This is similar to what GNOME does and it overall makes the applets and panel feel snappier. I don't think toggling popups is an action that would make a user hesitate and cancel when pressing the button so using `on_press_down()` should be fine.
Thanks!
> feat: toggle popups on press down

- cosmic-applet-bluetooth/src/app.rs
- cosmic-applet-bluetooth/src/bluetooth.rs
If `DeviceProperty::BatteryPercentage` is known, it gets indicated.
> add battery percentage indication to connected devices on bluetooth applet

- Cargo.lock
- cosmic-applet-audio/src/lib.rs
- cosmic-applet-network/src/app.rs
- cosmic-applet-notifications/src/lib.rs
- cosmic-applet-time/src/window.rs
Airplane mode can be off when Wi-Fi is off (e.g. when using Bluetooth), so this hides the non-functional visible networks button when both Wi-Fi and airplane mode are off.
Also includes minor fixes to better match designs, and makes the notifications applet a bit less squished.
> [Network] Don't show the visible networks button when Wi-Fi is off

- cosmic-applet-power/src/lib.rs
The current name is used in the Pop icon theme.
`system-reboot-symbolic` is used in the Cosmic and Adwaita icon themes.
Mainly to fix the slight background of the icon in the applet.
> [Power] Use correct restart icon

- Cargo.lock
- cosmic-applet-time/Cargo.toml
- cosmic-applet-time/src/window.rs
Closes: #582
The `chrono` crate [caches the local timezone](https://github.com/chronotope/chrono/blob/37ec019f8671d4c2c66d9b836d7eeea7b4709f89/src/offset/local/unix.rs#L31-L35) but doesn't update it. This makes sense because it'd be inefficient to constantly evaluate the local timezone.
Instead of using the local timezone, this patch changes the applet to use a fixed offset internally which is updated if the external timezone changes.
I added two new dependencies to the `time` applet.
* [pop-os/dbus-settings-bindings](https://github.com/pop-os/dbus-settings-bindings) for a wrapper around the D-Bus interface for timezone updates
* [chronotope/chrono-tz](https://github.com/chronotope/chrono-tz) for timezone information and parsing. This crate is maintained by the same developers as …
> fix(time): Update applet timezone on change

- cosmic-applet-time/src/config.rs
- cosmic-applet-time/src/window.rs
Closes: #496
Requires: pop-os/cosmic-settings#509
I based some of this code off of [i3status-rust](https://github.com/greshake/i3status-rust) to double check that I handled it efficiently.
> feat(time): Option to show seconds on the clock applet

- cosmic-applet-time/src/window.rs
See: [POSIX spec](https://pubs.opengroup.org/onlinepubs/9799919799/)
I noticed that GNOME used `LC_TIME` before checking `LANG` while working on my last two patches for greeter. It seems like the expected behavior as well even though it will usually be set to `LANG`.
I may have to annoyingly open a few very small PRs across COSMIC. :sweat_smile:
> time: Try LC_TIME before LANG

- cosmic-applet-audio/src/lib.rs
- cosmic-applet-battery/src/app.rs
- cosmic-applet-bluetooth/src/app.rs
- cosmic-applet-network/src/app.rs
- cosmic-applet-notifications/src/lib.rs
- cosmic-applet-power/src/lib.rs
- cosmic-applet-tiling/src/window.rs
- cosmic-applet-time/src/window.rs
Makes the Bluetooth pairing Confirm and Cancel button more closely match the design, and hides the **Other Bluetooth Devices** button if Bluetooth is off.
Switches most things to use `cosmic::widget::text`, instead of `cosmic::iced::widget::text`.
The iced version seems to be required in 2 places (audio and notifications; imported as `iced_text`), otherwise this error message is shown:
```
rustc: cannot return value referencing function parameter `options`
returns a value referencing data owned by the current function
```
> Minor fixes

- cosmic-applet-audio/src/pulse.rs
If you dragged the volume sliders in the audio applet, the applet panicked in `src/pulse.rs:158`.
This happened due to the communication channel to `PulseHandle` being bounded by a fixed size and hit with too much input.
I fixed it by only panicking if the channel was closed and only output a warning if it was full without panicking.
This however introduced lag to the volume sliders, which I fixed by deduplicating the messages that `PulseHandle` has to handle.
So that only the final volume will be set.
> fix: panic on mouse drag on volume sliders

- cosmic-applet-audio/src/mpris_subscription.rs
when using the plasma extension on firefox, player will be duplicated.  The` org.mpris.MediaPlayer2.plasma-browser-integration` gives better results
```
[mpris2/src/media_player.rs:40:3] &players = [
OwnedBusName::WellKnown(
"org.mpris.MediaPlayer2.firefox.instance_1_379",
),
OwnedBusName::WellKnown(
"org.mpris.MediaPlayer2.plasma-browser-integration",
),
]
Mozilla org.mozilla.firefox (org.mozilla.firefox)
Playback Status: Playing
Position: N/A
Doesn't support seeking
Supported Rates: N/A
Current Rate: N/A
Metadata: {xesam:artist: [""], xesam:title: "(30) Mac Miller - Self Care - YouTube", mpris:trackid: "/org/mpris/MediaPlayer2/firefox", xesam:album: ""}
Tracks: N/A
Playlists: N/A
[mpris2/examples/list.rs:18:3] media_player.inner().destination() = BusName::WellKnown( …
```
> improv: filter firefox player

- cosmic-app-list/Cargo.toml
- cosmic-applet-audio/Cargo.toml
- cosmic-applet-battery/Cargo.toml
- cosmic-applet-bluetooth/Cargo.toml
- cosmic-applet-input-sources/Cargo.toml
- cosmic-applet-minimize/Cargo.toml
- cosmic-applet-notifications/Cargo.toml
- cosmic-applet-power/Cargo.toml
- cosmic-applet-status-area/Cargo.toml
- cosmic-applet-tiling/Cargo.toml
- cosmic-applet-time/Cargo.toml
- cosmic-applet-workspaces/Cargo.toml
- cosmic-applets/Cargo.toml
- cosmic-panel-button/Cargo.toml
Fedora downstream packaging requires `GPL-3.0` to be clarified as either `GPL-3.0-or-later` or `GPL-3.0-only`
> chore(license): clarify GPL-3.0 license as GPL-3.0-only

- cosmic-applet-battery/src/dgpu.rs
Current dropdown menu when there is no application using the discrete GPU:
This is caused by the strange nvidia-smi output when nothing is running:
```
~$ nvidia-smi pmon --id 0:01:00.0 --count 1
0          -     -      -      -      -      -      -      -    -              
```
> Show empty dropdown menu when no app uses dGPU

- cosmic-applet-audio/src/lib.rs
> fix(audio-applet): Render input volume level instead of output.

- Cargo.toml
- cosmic-app-list/src/app.rs
- cosmic-applet-audio/src/lib.rs
- cosmic-applet-battery/src/app.rs
- cosmic-applet-bluetooth/src/app.rs
- cosmic-applet-input-sources/src/window.rs
- cosmic-applet-minimize/src/wayland_subscription.rs
- cosmic-applet-minimize/src/window_image.rs
- cosmic-applet-network/src/app.rs
- cosmic-applet-notifications/src/lib.rs
- cosmic-applet-notifications/src/subscriptions/dbus.rs
- cosmic-applet-power/src/lib.rs
- cosmic-applet-time/src/window.rs
- cosmic-applet-workspaces/src/components/app.rs
Makes the App Tray context menu use `@radius_s`, and also increases the truncate limit for the now playing title and artist in the audio applet.
The border at the corners still looks slightly weird with the Round style. Might be some rendering artifact.
Also includes some minor code cleanup.
> [App Tray] Use context menu radius from theme

- cosmic-applet-a11y/data/com.system76.CosmicAppletA11y.desktop
This commit fixes errors when using `desktop-file-validate` on the a11y applet.
Question: @wash2  I removed a duplicate keyword that had =Auto and =Center. Which one is the correct one to remove?
> fix: a11y applet desktop file validation

- cosmic-applet-time/src/window.rs
> fix: use `on_press_down` to toggle time applet

- cosmic-applet-audio/src/lib.rs
The COSMIC system settings provide a choice between 0-150% for the volume of both output and input. The COSMIC audio applet does not. 
This proposed change aligns the audio applet UI/UX with the system settings, allowing the user to "over-amplify" volume directly from the audio applet.
This change relates to the following issues:
* pop-os/cosmic-settings#484
* pop-os/cosmic-applets#625
Without this proposed change, or one of similar impact/change, a user could set volume to 150% in COSMIC settings and afterward, when adjusting volume via the audio applet, the volume will snap-back/cap to 100 and restrict volume to between 0-100%.
I understand there is a broader topic of how exactly to support "over-amplification", however, at minimum, the COSMIC audio applet should at least align with the …
> feat: audio applet over-amplification support

- Cargo.lock
- cosmic-applet-input-sources/Cargo.toml
- cosmic-applet-input-sources/src/lib.rs
- cosmic-applet-tiling/Cargo.toml
Closes: #725
The inputs applet uses an outdated `xkb-data` which causes some configs to fail which in turn leads to an empty list.
See: https://github.com/lilyinstarlight/nixos-cosmic/issues/74#issuecomment-2353273156
> fix(inputs): Use env vars and extra layouts

- cosmic-applet-network/src/app.rs
- cosmic-applet-network/src/network_manager/available_wifi.rs
- cosmic-applet-network/src/network_manager/current_networks.rs
- cosmic-applet-network/src/network_manager/hw_address.rs
- cosmic-applet-network/src/network_manager/mod.rs
Currently, if there are several wireless interfaces, there is no way to figure it out, which connection is being used(see picture below. There is no way to determine difference between 1 and 2 or 3 and 4 or 5 and 6).  
In addition to that, when trying to connect to some ssid, it will ALWAYS use the first wireless interface and so, there is no way to use the second one. So there is no actual way to connect to 2, only to 1
Fix contains several changes:
1) when connecting to wifi, it compares both ssid and iface of the connected wifi
2) it displays iface for ssid that is available on several interfaces
3) same rule applies to already connected wifi(see last image)
> Added interfaces to wifi

- Cargo.lock
- cosmic-app-list/src/app.rs
Fixes #456.
Also makes the border around the screencopy follow the edges of the image, rather than having a fixed size.
> [App Tray] Fix toplevel preview styling

- cosmic-applet-battery/src/backend/mod.rs
TuneD provides a compatibility daemon (tuned-ppd) which replaces power-profiles-daemon in Fedora 41 [1]. However, the new daemon can report an "unknown" profile in case the user manipulates with underlying TuneD profiles directly; see [2].
Before this change, the "unknown" profile makes the battery applet panic. With this change, the applet reports the balanced profile. This is in line with the behavior of cosmic-settings [3].
[1] https://pagure.io/fesco/issue/3222
[2] https://github.com/redhat-performance/tuned/pull/669
[3] https://github.com/pop-os/cosmic-settings/blob/6f05e9e/cosmic-settings/src/pages/power/backend/mod.rs#L65
> fix(battery): default to the balanced profile with PPD backend

- Cargo.lock
- Cargo.toml
- cosmic-app-list/src/app.rs
- cosmic-app-list/src/wayland_handler.rs
- cosmic-app-list/src/wayland_subscription.rs
- cosmic-applet-minimize/src/lib.rs
- cosmic-applet-minimize/src/wayland_handler.rs
- cosmic-applet-minimize/src/wayland_subscription.rs
- cosmic-applet-tiling/src/wayland.rs
Requires pop-os/cosmic-protocols#49.
The duplication between applets, and
cosmic-workspace/xdg-desktop-portal-cosmic, should be moved to shared abstractions. But that can be done after moving to `ext-image-copy-capture`.
> Update for toplevel-info cctk changes

- Cargo.lock
- Cargo.toml
this specifically allows the icon & actions to show in `cosmic-app-list` for librewolf - sorry for the spam!
> Bumping freedesktop-desktop-entry to 0.7.8

- Cargo.lock
- Cargo.toml
- cosmic-app-list/src/app.rs
- cosmic-app-list/src/wayland_handler.rs
- cosmic-app-list/src/wayland_subscription.rs
- cosmic-applet-minimize/src/wayland_handler.rs
- cosmic-applet-tiling/src/wayland.rs
- cosmic-applet-tiling/src/wayland_subscription.rs
- cosmic-applet-tiling/src/window.rs
- cosmic-applet-workspaces/src/components/app.rs
- cosmic-applet-workspaces/src/wayland.rs
- cosmic-applet-workspaces/src/wayland_subscription.rs
I still need to fix how the workspaces applet workspace, and how it lists and scrolls workspaces based on `coordinates`.
At some point we may want a shared subscription for workspaces in multiple applets. As well as a higher-level abstraction for screen capture.
> Update to workspace v2, based on ext-workspace

- cosmic-applet-battery/src/app.rs
Time remaining is briefly 0 after unplugging until the applet can calculate the remaining time. This fix prevents the time remaining showing if it's at 0 as this would only be just after unplugging (which is incorrect) or when the laptop is already dead.
> fix: prevent time remaining showing 0 after unplugging

- cosmic-applet-network/src/app.rs
This fixes the issue described here https://github.com/pop-os/cosmic-applets/issues/805
The .password() attribute on the secure_input was forcing the password to always be hidden regardless of setting. Removing this fixes the issue.
> fix: password hide/show on wifi authentication

- cosmic-applet-time/src/window.rs
Fixes https://github.com/pop-os/cosmic-applets/issues/875
'date_today' was not adjusting based on timezone and so its default value taken from UTC was persisting and causing incorrect day highlights in timezones very distant from UTC. This has been adapted so it updates based on the timezone in the same way the default value for 'date_selected' does.
> fix: current date highlight not respecting timezones

- cosmic-applet-time/src/window.rs
The calendar in the time applet is misaligned.
This PR fixes it.
> Fix time applet calendar alignment

- cosmic-applet-status-area/data/com.system76.CosmicAppletStatusArea.desktop
When running desktop-file-validate:
```
/builddir/build/BUILD/cosmic-applets-1.0.0_alpha.6_git20250408.2573eb7-build/BUILDROOT/usr/share/applications/com.system76.CosmicAppletStatusArea.desktop: error: file contains multiple keys named "Name[pt]" in group "Desktop Entry"
```
Fixes building for Fedora, as we use desktop-file-validate for checking desktop files.
Ref: https://github.com/pop-os/cosmic-applets/commit/2573eb7545e1619a9007c691df3dde0caa8edea9
I figured since this is the translation that was recently added, that the intent is to keep the newer one.
> Fix: Duplicate translation for cosmic-applet-status-area

- cosmic-panel-app-button/data/com.system76.CosmicPanelAppButton.desktop
- cosmic-panel-workspaces-button/data/com.system76.CosmicPanelWorkspacesButton.desktop
There were a few other duplicate [pt] translations that I found from https://github.com/pop-os/cosmic-applets/pull/894
Maybe it's worth having desktop-file-validate as part of a CI action, I dunno
> fix: Remove duplicate portuguese entries from desktop entries

- cosmic-applet-bluetooth/src/app.rs
- cosmic-applet-bluetooth/src/bluetooth.rs
- cosmic-applet-bluetooth/src/lib.rs
- cosmic-applet-bluetooth/src/localize.rs
Further improvement for #896
- Moves interval tick within `listen_bluetooth_power_changes` loop to throttle device change events
- Prevent double build of `build_device_list` in `listen_bluetooth_power_changes`
- Reuse Vec in `build_device_list`
- `BluerDevice` now directly stores only the properties it needs
- `BluerDevice` properties are fetched concurrently in a `join!()`
- `BluerDevice`s are also fetched concurrently from their addresses with `FuturesUnordered`
- Deduplicate bluer_state method with bluer_state function.
- Mark functions as inline/never
> perf(bluetooth): reduce CPU usage and improve async performance

- cosmic-applet-network/src/network_manager/mod.rs
fixes #909 
Looking at the logs, this seems to be what caused the applet to exit.
> fix(network): skip connections if getting settings fails

- cosmic-app-list/src/app.rs
**changes tl;dr**
- proton opens games with an appid of `steam_app_X` where `X` is either the steam appid or `default`
- since `steam_app_default` is a generic/catch-all, this adds some logic to capture an entry based off of its localised name
- this is seemingly the only way to properly detect these games without some overhauls to proton/game launchers
with fix:
without:
> App tray: add fallback logic for non-steam games opened in proton

- cosmic-applet-audio/src/lib.rs
- cosmic-applet-battery/src/app.rs
I don't know why it happens but wrapping the text widget inside a container fixes it.
Fixes #817 and #936
> fix text disappearing when moving sliders

- cosmic-applet-status-area/src/components/status_menu.rs
Some applications don't register an icon immediately and will register an icon with NewIcon later. This crashes the status-area when trying to create a pixmap from invalid data.
This PR solves this by setting dialog-question as a temporary icon, until hopefully getting a NewIcon update.
Possibly solves #951
> fix(status-area): prevent crash on invalid icon data

- cosmic-panel-button/src/lib.rs
After this change, only the XS panel should use the text form. Draft until this is confirmed if we want to do it.
> Use icon form for buttons on small panels

- cosmic-applet-a11y/src/main.rs
changed reference of battery to accessibility
> Fix typo in a11y main.rs logging

- cosmic-app-list/src/app.rs
- cosmic-app-list/src/wayland_handler.rs
- cosmic-app-list/src/wayland_subscription.rs
- cosmic-applet-a11y/src/app.rs
- cosmic-applet-audio/src/lib.rs
- cosmic-applet-audio/src/mpris_subscription.rs
- cosmic-applet-audio/src/pulse.rs
- cosmic-applet-battery/src/app.rs
- cosmic-applet-battery/src/dgpu.rs
- cosmic-applet-bluetooth/src/app.rs
- cosmic-applet-bluetooth/src/bluetooth.rs
- cosmic-applet-input-sources/src/lib.rs
- cosmic-applet-minimize/src/lib.rs
- cosmic-applet-minimize/src/wayland_handler.rs
- cosmic-applet-network/src/app.rs
- cosmic-applet-network/src/network_manager/available_wifi.rs
- cosmic-applet-network/src/network_manager/current_networks.rs
- cosmic-applet-network/src/network_manager/mod.rs
- cosmic-applet-notifications/src/lib.rs
- cosmic-applet-notifications/src/subscriptions/notifications.rs
- cosmic-applet-status-area/src/components/app.rs
- cosmic-applet-tiling/src/window.rs
- cosmic-applet-time/src/window.rs
- cosmic-applet-workspaces/src/components/app.rs
Some minor refactors like removing `clone()`s, replacing with references, avoiding allocating `Vec`s when they weren't necessary, etc.
There's also a new `std::cmp::Ord` impl for `ActiveConnectionInfo`, which should be heaps better than using `format!`. I had to also impl `std::cmp::PartialCmp` manually to do that, but the actual logic there shouldn't matter as long as it agrees with `std::cmp::Ord`.
> perf: refactor to reduce memory allocations
